# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-09 11:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Subject')),
                ('date', models.DateTimeField(null=True, verbose_name='Data and time of event')),
                ('teacher_name', models.CharField(max_length=256, verbose_name='Lecturer')),
                ('notes', models.TextField(blank=True, verbose_name='Additional notes')),
                ('is_completed', models.BooleanField(default=False)),
                ('time_change', models.DateTimeField(auto_now=True, verbose_name='Time of last modification')),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('title_uk', models.CharField(max_length=256, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=256, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=256, null=True, verbose_name='Title')),
                ('notes', models.TextField(blank=True, verbose_name='Additional notes')),
                ('time_change', models.DateTimeField(auto_now=True, verbose_name='Time of last modification')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group_requests_created', to=settings.AUTH_USER_MODEL, verbose_name='User who created')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_datetime', models.DateTimeField(verbose_name='Date and time')),
                ('status', models.CharField(max_length=256, verbose_name='Status')),
                ('signal', models.CharField(max_length=256, verbose_name='Signal name')),
                ('info', models.CharField(max_length=256, verbose_name='Signal text')),
                ('time_change', models.DateTimeField(auto_now=True, verbose_name='Time of last modification')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logentry_requests_created', to=settings.AUTH_USER_MODEL, verbose_name='User who created')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logentry_requests_modified', to=settings.AUTH_USER_MODEL, verbose_name='User who modified')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='MonthJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('present_day1', models.BooleanField(default=False)),
                ('present_day2', models.BooleanField(default=False)),
                ('present_day3', models.BooleanField(default=False)),
                ('present_day4', models.BooleanField(default=False)),
                ('present_day5', models.BooleanField(default=False)),
                ('present_day6', models.BooleanField(default=False)),
                ('present_day7', models.BooleanField(default=False)),
                ('present_day8', models.BooleanField(default=False)),
                ('present_day9', models.BooleanField(default=False)),
                ('present_day10', models.BooleanField(default=False)),
                ('present_day11', models.BooleanField(default=False)),
                ('present_day12', models.BooleanField(default=False)),
                ('present_day13', models.BooleanField(default=False)),
                ('present_day14', models.BooleanField(default=False)),
                ('present_day15', models.BooleanField(default=False)),
                ('present_day16', models.BooleanField(default=False)),
                ('present_day17', models.BooleanField(default=False)),
                ('present_day18', models.BooleanField(default=False)),
                ('present_day19', models.BooleanField(default=False)),
                ('present_day20', models.BooleanField(default=False)),
                ('present_day21', models.BooleanField(default=False)),
                ('present_day22', models.BooleanField(default=False)),
                ('present_day23', models.BooleanField(default=False)),
                ('present_day24', models.BooleanField(default=False)),
                ('present_day25', models.BooleanField(default=False)),
                ('present_day26', models.BooleanField(default=False)),
                ('present_day27', models.BooleanField(default=False)),
                ('present_day28', models.BooleanField(default=False)),
                ('present_day29', models.BooleanField(default=False)),
                ('present_day30', models.BooleanField(default=False)),
                ('present_day31', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Month Journal',
                'verbose_name_plural': 'Month Journals',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='Mark')),
                ('time_change', models.DateTimeField(auto_now=True, verbose_name='Time of last modification')),
                ('result_exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='students.Exam', verbose_name='Subject')),
            ],
            options={
                'verbose_name': 'Exam results',
                'verbose_name_plural': 'Exams results',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256, verbose_name='First Name')),
                ('first_name_uk', models.CharField(max_length=256, null=True, verbose_name='First Name')),
                ('first_name_en', models.CharField(max_length=256, null=True, verbose_name='First Name')),
                ('first_name_ru', models.CharField(max_length=256, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=256, verbose_name='Last Name')),
                ('last_name_uk', models.CharField(max_length=256, null=True, verbose_name='Last Name')),
                ('last_name_en', models.CharField(max_length=256, null=True, verbose_name='Last Name')),
                ('last_name_ru', models.CharField(max_length=256, null=True, verbose_name='Last Name')),
                ('middle_name', models.CharField(blank=True, default='', max_length=256, verbose_name='Middle Name')),
                ('birthday', models.DateField(null=True, verbose_name='Birthday')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='Photo')),
                ('ticket', models.IntegerField(unique=True, verbose_name='Ticket')),
                ('notes', models.TextField(blank=True, verbose_name='Additional notes')),
                ('time_change', models.DateTimeField(auto_now=True, verbose_name='Time of last modification')),
                ('student_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='students.Group', verbose_name='Group')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.AddField(
            model_name='result',
            name='result_student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Student', verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='student_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student', unique_for_month='date', verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='group',
            name='leader',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.Student', verbose_name='Leader'),
        ),
        migrations.AddField(
            model_name='group',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group_requests_modified', to=settings.AUTH_USER_MODEL, verbose_name='User who modified'),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Group', verbose_name='Group'),
        ),
    ]
