# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20161124_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='notes',
            field=models.TextField(blank=True, verbose_name='\u0414\u043e\u0434\u0430\u0442\u043a\u043e\u0432\u0456 \u043d\u043e\u0442\u0430\u0442\u043a\u0438'),
        ),
    ]
