# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_exam_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.DateField(help_text='\u043d\u0430\u043f\u0440. 1984-06-17', null=True, verbose_name='\u0414\u0430\u0442\u0430 \u043d\u0430\u0440\u043e\u0434\u0436\u0435\u043d\u043d\u044f'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(help_text="\u0412\u0432\u0435\u0434\u0456\u0442\u044c \u0456\u043c'\u044f \u0441\u0442\u0443\u0434\u0435\u043d\u0442\u0430", max_length=256, verbose_name='\u0406\u043c\u2019\u044f'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(help_text='\u0412\u0432\u0435\u0434\u0456\u0442\u044c \u043f\u0440\u0456\u0437\u0432\u0438\u0449\u0435 \u0441\u0442\u0443\u0434\u0435\u043d\u0442\u0430', max_length=256, verbose_name='\u041f\u0440\u0456\u0437\u0432\u0438\u0449\u0435'),
        ),
        migrations.AlterField(
            model_name='student',
            name='middle_name',
            field=models.CharField(blank=True, default='', help_text="\u0412\u0432\u0435\u0434\u0456\u0442\u044c \u0456\u043c'\u044f \u043f\u043e-\u0431\u0430\u0442\u044c\u043a\u043e\u0432\u0456 \u0441\u0442\u0443\u0434\u0435\u043d\u0442\u0430", max_length=256, verbose_name='\u041f\u043e-\u0431\u0430\u0442\u044c\u043a\u043e\u0432\u0456'),
        ),
        migrations.AlterField(
            model_name='student',
            name='ticket',
            field=models.CharField(help_text='\u043d\u0430\u043f\u0440. 123', max_length=256, verbose_name='\u0411\u0456\u043b\u0435\u0442'),
        ),
    ]
