# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-30 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_monthjournal'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
