# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-10 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_exam_is_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_datetime', models.DateTimeField(verbose_name='\u0414\u0430\u0442\u0430 \u0442\u0430 \u0447\u0430\u0441')),
                ('status', models.CharField(max_length=256, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441')),
                ('signal', models.CharField(max_length=256, verbose_name='\u041d\u0430\u0437\u0432\u0430 \u0441\u0438\u0433\u043d\u0430\u043b\u0443')),
                ('info', models.CharField(max_length=256, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0441\u0438\u0433\u043d\u0430\u043b\u0443')),
            ],
            options={
                'verbose_name': '\u041b\u043e\u0433\u0438 \u0437\u0430 \u0434\u0435\u043d\u044c',
                'verbose_name_plural': '\u041b\u043e\u0433\u0438 \u0437\u0430 \u0434\u043d\u0456',
            },
        ),
    ]
