# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-11 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_logentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logentry',
            options={'verbose_name': '\u041f\u043e\u0434\u0456\u044f', 'verbose_name_plural': '\u041f\u043e\u0434\u0456\u0457'},
        ),
    ]
