# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-12 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_auto_20170111_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='ticket',
            field=models.IntegerField(unique=True, verbose_name='\u0411\u0456\u043b\u0435\u0442'),
        ),
    ]
