# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-28 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_auto_20170128_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='time_zone',
            field=models.CharField(blank=True, max_length=128, verbose_name='Time Zone'),
        ),
    ]
