# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-29 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_auto_20170128_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='time_change',
            field=models.DateTimeField(auto_now=True, verbose_name='Time of last modification'),
        ),
        migrations.AddField(
            model_name='group',
            name='time_change',
            field=models.DateTimeField(auto_now=True, verbose_name='Time of last modification'),
        ),
        migrations.AddField(
            model_name='result',
            name='time_change',
            field=models.DateTimeField(auto_now=True, verbose_name='Time of last modification'),
        ),
        migrations.AddField(
            model_name='student',
            name='time_change',
            field=models.DateTimeField(auto_now=True, verbose_name='Time of last modification'),
        ),
    ]
