# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-29 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_auto_20170129_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='first_name_en',
            field=models.CharField(max_length=256, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='student',
            name='first_name_ru',
            field=models.CharField(max_length=256, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='student',
            name='first_name_uk',
            field=models.CharField(max_length=256, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name_en',
            field=models.CharField(max_length=256, null=True, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name_ru',
            field=models.CharField(max_length=256, null=True, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name_uk',
            field=models.CharField(max_length=256, null=True, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='student',
            name='middle_name_en',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Middle Name'),
        ),
        migrations.AddField(
            model_name='student',
            name='middle_name_ru',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Middle Name'),
        ),
        migrations.AddField(
            model_name='student',
            name='middle_name_uk',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Middle Name'),
        ),
    ]
