# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-04 05:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_auto_20170129_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='middle_name_en',
        ),
        migrations.RemoveField(
            model_name='student',
            name='middle_name_ru',
        ),
        migrations.RemoveField(
            model_name='student',
            name='middle_name_uk',
        ),
    ]
