# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-13 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_migrate_activatedstatus'),
        ('admin', '0002_logentry_remove_auto_add'),
        ('students', '0018_auto_20170204_0550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainuser',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='MainUser',
        ),
    ]
