# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-22 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud_auth', '0004_auto_20170624_1550'),
        ('social_django', '0006_partial'),
        ('admin', '0002_logentry_remove_auto_add'),
        ('registration', '0004_supervisedregistrationprofile'),
        ('students', '0018_auto_20170204_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='title_en',
            field=models.CharField(max_length=256, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='group',
            name='title_ru',
            field=models.CharField(max_length=256, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='group',
            name='title_uk',
            field=models.CharField(max_length=256, null=True, verbose_name='Title'),
        ),
    ]
