# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-02 10:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stud_auth', '0004_auto_20170624_1550'),
        ('social_django', '0006_partial'),
        ('admin', '0002_logentry_remove_auto_add'),
        ('registration', '0004_supervisedregistrationprofile'),
        ('students', '0019_auto_20170822_1751'),
    ]

    operations = [
    ]
