# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-09 10:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stud_auth', '0004_auto_20170624_1550'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin', '0002_logentry_remove_auto_add'),
        ('registration', '0004_supervisedregistrationprofile'),
        ('social_django', '0006_partial'),
        ('students', '0019_auto_20170822_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainuser',
            name='user_ptr',
        ),
        migrations.AlterModelOptions(
            name='logentry',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AddField(
            model_name='group',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group_requests_created', to=settings.AUTH_USER_MODEL, verbose_name='User who created'),
        ),
        migrations.AddField(
            model_name='group',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group_requests_modified', to=settings.AUTH_USER_MODEL, verbose_name='User who modified'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logentry_requests_created', to=settings.AUTH_USER_MODEL, verbose_name='User who created'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logentry_requests_modified', to=settings.AUTH_USER_MODEL, verbose_name='User who modified'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='time_change',
            field=models.DateTimeField(auto_now=True, verbose_name='Time of last modification'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='info',
            field=models.CharField(max_length=256, verbose_name='Signal text'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='log_datetime',
            field=models.DateTimeField(verbose_name='Date and time'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='signal',
            field=models.CharField(max_length=256, verbose_name='Signal name'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='status',
            field=models.CharField(max_length=256, verbose_name='Status'),
        ),
        migrations.DeleteModel(
            name='MainUser',
        ),
    ]
