# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-02 10:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stud_auth', '0004_auto_20170624_1550'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin', '0002_logentry_remove_auto_add'),
        ('registration', '0004_supervisedregistrationprofile'),
        ('social_django', '0006_partial'),
        ('students', '0020_auto_20170902_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group_requests_created', to=settings.AUTH_USER_MODEL, verbose_name='User who created'),
        ),
        migrations.AddField(
            model_name='group',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group_requests_modified', to=settings.AUTH_USER_MODEL, verbose_name='User who modified'),
        ),
        migrations.DeleteModel(
            name='MainUser',
        ),
    ]
