# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-09 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0023_logentry_time_change'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logentry',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterField(
            model_name='logentry',
            name='info',
            field=models.CharField(max_length=256, verbose_name='Signal text'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='log_datetime',
            field=models.DateTimeField(verbose_name='Date and time'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='signal',
            field=models.CharField(max_length=256, verbose_name='Signal name'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='status',
            field=models.CharField(max_length=256, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='time_change',
            field=models.DateTimeField(auto_now=True, verbose_name='Time of last modification'),
        ),
    ]
