# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-01 17:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_phone', models.CharField(blank=True, default=b'', max_length=12, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u041c\u043e\u0431\u0456\u043b\u044c\u043d\u043e\u0433\u043e')),
                ('address', models.CharField(blank=True, max_length=256, verbose_name='\u0410\u0434\u0440\u0435\u0441\u0430')),
                ('passport', models.CharField(blank=True, max_length=20, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u041f\u0430\u0441\u043f\u043e\u0440\u0442\u0443')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u041f\u0440\u043e\u0444\u0456\u043b\u044c \u041a\u043e\u0440\u0438\u0441\u0442\u0443\u0432\u0430\u0447\u0430',
            },
        ),
    ]
