# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-24 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud_auth', '0003_auto_20170302_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stprofile',
            name='language',
            field=models.CharField(blank=True, default=b'', max_length=10, verbose_name='\u041c\u043e\u0432\u0430'),
        ),
        migrations.AlterField(
            model_name='stprofile',
            name='mobile_phone',
            field=models.CharField(blank=True, default=b'', max_length=12, verbose_name='\u041c\u043e\u0431\u0456\u043b\u044c\u043d\u0438\u0439 \u0422\u0435\u043b\u0435\u0444\u043e\u043d'),
        ),
        migrations.AlterField(
            model_name='stprofile',
            name='time_zone',
            field=models.CharField(blank=True, default=b'', max_length=128, verbose_name='\u0427\u0430\u0441\u043e\u0432\u0430 \u0437\u043e\u043d\u0430'),
        ),
    ]
