# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-25 08:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stud_auth', '0004_auto_20170624_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stprofile',
            options={'permissions': (('view_exams', 'Can view list of exams'),), 'verbose_name': '\u041f\u0440\u043e\u0444\u0456\u043b\u044c \u041a\u043e\u0440\u0438\u0441\u0442\u0443\u0432\u0430\u0447\u0430'},
        ),
    ]
